Projects/Dockerize-Django-App/LocalLibrary2/LocalLibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_header = "Public Library Administration"
admin.site.site_title = "Public Library Admin"
admin.site.index_title = "Welcome to Public Library Admin Page"

Projects/Dockerize-Django-App/LocalLibrary2/catalog/urls.py
from django.urls import path
from .import views
from .views import (BookListView,BookDetailView,AuthorListView,AuthorDetailView,LoanedBooksByUserListView,
	LoanedBooksAllListView,AuthorCreate,AuthorUpdate,AuthorDelete,BookCreate,BookUpdate,BookDelete,
	GenreCreate,GenreUpdate,GenreDelete,BookInstanceCreate,BookInstanceUpdate,BookInstanceDelete,
	GenreListView,RegistrationForm)

app_name = 'catalog'

urlpatterns = [
	path('', views.index, name='index'),
	path('books/', BookListView.as_view(), name='books'),
	path('book/<int:pk>',BookDetailView.as_view(), name='book-detail'),
	path('authors/', AuthorListView.as_view(), name='authors'),
	path('author/<int:pk>',AuthorDetailView.as_view(), name='author-detail'),
	path('genres/', GenreListView.as_view(), name='genres'),
	path('genre/<str:name>', views.detail, name='genre-detail'),
	path('mybooks/', LoanedBooksByUserListView.as_view(), name='my-borrowed'),
	path(r'borrowed/', LoanedBooksAllListView.as_view(), name='all-borrowed'),
	path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
	path('author/create/', AuthorCreate.as_view(), name='author_create'),
        path('author/<int:pk>/update/', AuthorUpdate.as_view(), name='author_update'),
        path('author/<int:pk>/delete/', AuthorDelete.as_view(), name='author_delete'),
        path('book/create/', BookCreate.as_view(), name='book_create'),
        path('book/<int:pk>/update/', BookUpdate.as_view(), name='book_update'),
        path('book/<int:pk>/delete/', BookDelete.as_view(), name='book_delete'),
        path('genre/create/', GenreCreate.as_view(), name='genre_create'),
        path('genre/<int:pk>/update/',GenreUpdate.as_view(), name='genre_update'),
        path('genre/<int:pk>/delete/', GenreDelete.as_view(), name='genre_delete'),
        path('book_instance/create/', BookInstanceCreate.as_view(), name='book_instance_create'),
        path('book_instance/<uuid:pk>/update/',BookInstanceUpdate.as_view(), name='book_instance_update'),
        path('book_instance/<uuid:pk>/delete/', BookInstanceDelete.as_view(), name='book_instance_delete'),
        path('signup/', views.register, name='signup'),
]

Projects/Dockerize-Django-App/LocalLibrary2/catalog/models.py
from django.db import models
from django.urls import reverse 	# Used to generate URLs by reversing the URL patterns
import uuid 
from django.contrib.auth.models import User		
from datetime import date

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True,help_text='YYYY-MM-D')
    date_of_death = models.DateField('died', null=True, blank=True,help_text='YYYY-MM-D')

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        #catalog/author/1
        return reverse('catalog:author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'


class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')
    
    def __str__(self):
        return self.name

class Language(models.Model):
 	name = models.CharField(max_length=200, help_text='Enter book language')

 	def __str__(self):
 		return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    language=models.ForeignKey(Language, on_delete=models.SET_NULL,null=True)
    
    def __str__(self):
        return self.title
    
    #Returns the url to access a detail record for this book
    def get_absolute_url(self):
        return reverse('catalog:book-detail', args=[str(self.id)])


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True) 
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)  #tuple(permission name,permission display value)
        #The current user's permissions are stored in a template variable called {{ perms }}.
        
    def __str__(self):
        return f'{self.id} ({self.book.title})'



 

Projects/Dockerize-Django-App/LocalLibrary2/catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")
    print("renew",renewal_date)

    #defining validations
    def clean_renewal_date(self): #easiest way to validate a field is to override method by this func for the field u want to check
        data = self.cleaned_data['renewal_date']  #date which is extracted after submitting form textarea
        print("data22",data)
        
        # Check if a date is not in the past. 
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

class RegistrationForm(UserCreationForm):
 
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']

        def clean_form(self):
            first_name = self.cleaned_data['first_name']
            last_name = self.cleaned_data['last_name']
            email = self.cleaned_data['email']

            return first_name,last_name,email

Projects/Dockerize-Django-App/LocalLibrary2/catalog/views.py
from django.shortcuts import render
from catalog.models import Book, Author, BookInstance, Genre, Language 
from django.shortcuts import get_object_or_404
from django.views.generic import (ListView,DetailView)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
import datetime
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from catalog.forms import RenewBookForm,RegistrationForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth.models import User

def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()    
    num_authors = Author.objects.count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
    }

    return render(request, 'catalog/index.html', context=context)


class BookListView(ListView):
    model = Book
    paginate_by = 6

    def get_queryset(self):
        return Book.objects.all().order_by('title')
   


class BookDetailView(DetailView):
    model = Book


class AuthorListView(ListView):
	model = Author
	paginate_by = 6
	
	def get_queryset(self):
		return Author.objects.all().order_by('last_name')


class AuthorDetailView(DetailView):
	model = Author


class GenreListView(ListView):
    model = Genre
    paginate_by = 6

    def get_queryset(self):
        return Genre.objects.all().order_by('name')
    

def detail(request,name):
    Books = Book.objects.filter(genre__name=name)
    context = {'Books':Books,'name':name}
    return render(request , 'catalog/bookgenre.html',context)


class LoanedBooksByUserListView(LoginRequiredMixin,ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 6
    
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


class LoanedBooksAllListView(PermissionRequiredMixin,ListView):
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    paginate_by = 6

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)
    print("bukin",book_instance)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)
        print("formsss",form)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            print("a",form.cleaned_data['renewal_date'])  #saved date
            book_instance.save()


    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        print("proposed",proposed_renewal_date)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)


class AuthorCreate(PermissionRequiredMixin,CreateView):
    model = Author
    fields = '__all__'
    permission_required = 'catalog.can_mark_returned'
    initial = {'date_of_death': '05/01/2018'}
    success_url = '/catalog/authors/'

class AuthorUpdate(PermissionRequiredMixin,UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    permission_required = 'catalog.can_mark_returned'
    success_url = '/catalog/authors/'

class AuthorDelete(PermissionRequiredMixin,DeleteView):
    model = Author
    permission_required = 'catalog.can_mark_returned'
    success_url = '/catalog/authors/'

class BookCreate(PermissionRequiredMixin,CreateView):
    model = Book
    fields = '__all__'
    permission_required = 'catalog.can_mark_returned'
    success_url = '/catalog/books/'

class BookUpdate(PermissionRequiredMixin,UpdateView):
    model = Book
    fields = '__all__'
    permission_required = 'catalog.can_mark_returned'
    success_url = '/catalog/books/'

class BookDelete(PermissionRequiredMixin,DeleteView):
    model = Book
    permission_required = 'catalog.can_mark_returned'
    success_url = '/catalog/books/'

class GenreCreate(PermissionRequiredMixin,CreateView):
    model = Genre
    permission_required = 'catalog.can_mark_returned'
    fields = '__all__'
    success_url = '/catalog/genres/'

class GenreUpdate(PermissionRequiredMixin,UpdateView):
    model = Genre
    permission_required = 'catalog.can_mark_returned'
    fields = '__all__'
    success_url = '/catalog/genres/'

class GenreDelete(PermissionRequiredMixin,DeleteView):
    model = Genre
    permission_required = 'catalog.can_mark_returned'
    success_url = '/catalog/genre/'

class BookInstanceCreate(PermissionRequiredMixin,CreateView):
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    fields = '__all__'
    success_url = '/catalog/borrowed/'

class BookInstanceUpdate(PermissionRequiredMixin,UpdateView):
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    fields = '__all__'
    success_url = '/catalog/borrowed/'

class BookInstanceDelete(PermissionRequiredMixin,DeleteView):
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    success_url = '/catalog/borrowed/'


from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

def register(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('catalog:my-borrowed') )

    else:
        form = RegistrationForm()

    arg = {'form':form}
    return render(request,'catalog/signup.html',arg)

Projects/Dockerize-Django-App/LocalLibrary2/catalog/templates/catalog/author_confirm_delete.html
{% extends "catalog/base_generic.html" %}

{% block content %}

<div class="col-sm-7 mx-5">

	<h2>Delete Author</h2>
	<p>Are you sure you want to delete the author: {{ author }}?</p>

	<form action="" method="POST">
  		{% csrf_token %}
  		<button class="btn btn-info" type="submit"> Yes, delete</button>
	</form>

</div>

{% endblock %}

Projects/Dockerize-Django-App/LocalLibrary2/catalog/templates/catalog/author_form.html
<!-- this template is for both update and create view -->
{% extends 'catalog/base_generic.html' %}
{% block content %}

<style> 
        input{ 
            width:100%; 
            padding: 12px; 
            } 
</style> 

<div class="col-sm-7 mx-5">
    <h2>Add Authors</h2>
</div>

<form method="post">
  
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group row mx-5 mt-4">
      <div class="col-sm-2 col-form-label">{{ field.label_tag }}</div>
        <div class="col-sm-7">
          {{field}} <br>
          {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        </div>
    </div>
  {% endfor %}

<div class="form-group row mx-5">
    <button type="submit" class="btn btn-info btn-block">Submit</button>
</div>

</form>
{% endblock %}

Projects/Dockerize-Django-App/LocalLibrary2/catalog/templates/catalog/author_list.html
{% extends "catalog/base_generic.html" %}
{% block content %}

<div class="col-sm-7 mx-5">
  <h2>All Authors</h2> <hr/>

  {% if author_list %}
    {% for author in author_list %}
      <p class="text-info"><a href="{% url 'catalog:author-detail' author.id %}">{{ author }} ({{author.date_of_birth}})</a> </p> <hr/>

      {% if perms.catalog.delete_author and perms.catalog.change_author %}
          <button class="btn btn-info btn-sm"><a href="{% url 'catalog:author_delete' author.id %}">Delete author</a></button>
          <button class="btn btn-info btn-sm"><a href="{% url 'catalog:author_update' author.id %}">Update author</a></button>
          <hr/>
      {% endif %}
      
    {% endfor %}
  {% else %}
    <p>No Author</p>
  {% endif %}       
  
{% endblock %}

Projects/Dockerize-Django-App/LocalLibrary2/catalog/templates/catalog/book_confirm_delete.html
{% extends "catalog/base_generic.html" %}
{% block content %}

<div class="col-sm-7 mx-5">
<h2>Delete Book</h2>
<p>Are you sure you want to delete the book: {{ Book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <button class="btn btn-info" type="submit"> Yes, delete</button>
</form>

</div>

{% endblock %}

Projects/Dockerize-Django-App/LocalLibrary2/catalog/templates/catalog/book_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}

<h2>Title: {{ book.title }}</h2> <hr/>
<p class="text-info"><strong>Author:</strong> <a href="{% url 'catalog:author-detail' book.author.pk %}">{{ book.author }}</a></p>
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p> 
<p><strong>Language:</strong> {{ book.language }}</p>  
<p><strong>Genre:</strong> 

{% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
      <h4>Copies</h4>
      {% for copy in book.bookinstance_set.all %}  <!-- related object to bookinstance -->
        <hr>
        <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>

        {% if copy.status != 'a' %}
          <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
        {% endif %}

        <p><strong>Imprint:</strong> {{copy.imprint}}</p>
        <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
      {% endfor %}
  </div>
  
{% endblock %}

Projects/Dockerize-Django-App/LocalLibrary2/catalog/templates/catalog/book_list.html
{% extends "catalog/base_generic.html" %}
{% block content %}

<div class="col-sm-7 mx-5">
  <h2>All Books </h2> <hr/>
  
  {% if book_list %}
    {% for book in book_list %}
        <p class="text-info"><a href="{% url 'catalog:book-detail' book.id %}">{{ book.title }} ({{book.author}})</a> </p> <hr/>
      
        {% if perms.catalog.delete_book and perms.catalog.change_book %}
          <button class="btn btn-info btn-sm"><a href="{% url 'catalog:book_delete' book.id %}">Delete book</a>
          </button>
          <button class="btn btn-info btn-sm"><a href="{% url 'catalog:book_update' book.id %}">Update book</a>
          </button>
          <hr/>
        {% endif %}
        
    {% endfor %}
  
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}

</div>    

{% endblock %}

Projects/Dockerize-Django-App/LocalLibrary2/catalog/templates/catalog/book_renew_librarian.html
{% extends "catalog/base_generic.html" %}
{% block content %}

<style> 
        input{ 
            width:100%; 
            padding: 12px; 
            } 
</style>

<div class="col-sm-7 mx-5">
  <h1>Renew: {{ book_instance.book_title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>
</div>
    
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group row mx-5 mt-4">
      <div class="col-sm-2 col-form-label">{{ field.label_tag }}</div>
        <div class="col-sm-7">
          {{field}} <br>
          {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        </div>
    </div>
    {% endfor %}

  
  <div class="form-group row mx-5">
    <div class="col-sm-7">
      <button type="submit" class="btn btn-info">Submit</button>
    </div>
  </div>
</form>
{% endblock %}

Projects/Dockerize-Django-App/LocalLibrary2/catalog/templates/catalog/bookinstance_confirm_delete.html
{% extends "catalog/base_generic.html" %}
{% block content %}

<div class="col-sm-7 mx-5">
	<h2>Are You Sure User Return This Book {{bookinstance.book}}</h2>

	<form action="" method="POST">
  		{% csrf_token %}
  		<button class="btn btn-info" type="submit"> Yes, delete</button>
	</form>
	
</div>

{% endblock %}

Projects/Dockerize-Django-App/LocalLibrary2/catalog/templates/catalog/bookinstance_form.html
{% extends "catalog/base_generic.html" %}
{% block content %}

  <style> 
        input{ 
            width:100%; 
            padding: 12px; 
            } 
    </style> 

{% block extrahead %}
  {{ block.super }}
  <style type="text/css">
      #id_book , #id_status , #id_borrower 
      { width: 100%;
      padding: 12px; }
  </style>
{% endblock %}

<div class="col-sm-7 mx-5">
    <h2>Book Instance</h2>
</div>

<form method="post">
  	{% csrf_token %}
  	{% for field in form %}
      <div class="form-group row mx-5 mt-4">
        <div class="col-sm-2 col-form-label">{{ field.label_tag }}</div>
          <div class="col-sm-7">
            {{field}} <br>
            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}

            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </div>
      </div>
    {% endfor %}

  <div class="form-group row mx-5">
    <div class="col-sm-7">
      <button type="submit" class="btn btn-info">Submit</button>
    </div>
  </div>
</form>

{% endblock %}

Projects/Dockerize-Django-App/LocalLibrary2/catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "catalog/base_generic.html" %}
{% block content %}

<div class="col-sm-7 mx-5">
  {% if perms.catalog.can_mark_returned %}
    <h2>All Borrowed Books</h2><hr/>
    {% if bookinstance_list %}
      {% for bookinst in bookinstance_list %} 
        <p class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'catalog:book-detail' bookinst.book.pk %}">{{bookinst.book.title}} ({{ bookinst.due_back }}) - {{ bookinst.borrower }}</a> 
        </p>
        <button class="btn btn-info btn-sm"><a href="{% url 'catalog:renew-book-librarian' bookinst.id %}">Renew</a> </button>
        <button class="btn btn-info btn-sm"><a href="{% url 'catalog:book_instance_delete' bookinst.id %}">Delete if book returned</a> </button> <hr/>
      {% endfor %}
    
    {% else %} 
      <p>There are no books borrowed.</p>
    {% endif %}  
  {% endif %}  
</div>

{% endblock %}

Projects/Dockerize-Django-App/LocalLibrary2/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "catalog/base_generic.html" %}
{% block content %}

<div class="col-sm-7 mx-5">
  <h2>Borrowed books</h2><hr/>
  {% if bookinstance_list %}
    {% for bookinst in bookinstance_list %} 
      <p class="{% if bookinst.is_overdue %}text-danger{% endif %}">
      <a href="{% url 'catalog:book-detail' bookinst.book.pk %}">{{bookinst.book.title}} ({{ bookinst.due_back }}) </a> 
      </p><hr/>
    {% endfor %}
  {% else %}
      <p>There are no books borrowed.</p>
  {% endif %}  
</div> 

{% endblock %}

Projects/Dockerize-Django-App/LocalLibrary2/catalog/templates/catalog/genre_form.html
{% extends "catalog/base_generic.html" %}
{% block content %}

<style> 
        input{ 
            width:100%; 
            padding: 12px; 
            } 
    </style>

<div class="col-sm-7 mx-5">
  <h2>Add Genre</h2>
</div>

<form method="post">
  	{% csrf_token %}
  	{% for field in form %}
      <div class="form-group row mx-5 mt-4">
        <div class="col-sm-2 col-form-label">{{ field.label_tag }}</div>
          <div class="col-sm-7">
            {{field}} <br>
            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </div>
      </div>  
    {% endfor %}

    <div class="form-group row mx-5">
      <button type="submit" class="btn btn-info btn-block">Submit</button>
    </div>
</form>

{% endblock %}

Projects/Dockerize-Django-App/LocalLibrary2/catalog/templates/catalog/genre_list.html
{% extends "catalog/base_generic.html" %}
{% block content %}

<div class="col-sm-7 mx-5">
  <h2>Genre List</h2> <hr/>
  {% if genre_list %}
    {% for genre in genre_list %}
      <p class="text-info"><a href="{% url 'catalog:genre-detail' genre.name %}">{{ genre }} </a> </p><hr/>
      {% if perms.catalog.delete_author and perms.catalog.change_author %}
        <button class="btn btn-info btn-sm"><a href="{% url 'catalog:genre_delete' genre.id %}">Delete genre</a></button>
        <button class="btn btn-info btn-sm"><a href="{% url 'catalog:genre_update' genre.id %}">Update genre</a></button>
        <hr/>
      {% endif %}
    {% endfor %}
  {% else %}
    <p>No Genre</p>
  {% endif %}  
</div>
     
{% endblock %}

Projects/Dockerize-Django-App/LocalLibrary2/catalog/templates/catalog/signup.html
{% extends 'catalog/base_generic.html' %}
{% block content %}

<style> 
        input{ 
            width:100%; 
            padding: 12px; 
            } 
    </style> 

<div class="col-sm-7">
  <h2>Sign up</h2> </div><hr/>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group row mt-4 ">
        <div class="col-sm-2 col-form-label">{{ field.label_tag }}</div>
          <div class="col-sm-7">
            {{field}} <br>
            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </div>
      </div>
    {% endfor %}
  
    <div class="form-group row">
      <button type="submit" class="btn btn-info btn-block">Sign up</button>
    </div>
</form>

{% endblock %}